
AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION_NAME = "AWS_REGION"
S3_TRAINING_BUCKET_NAME = "bsb4018-rec-sys-app"
MONGODB_URL_KEY = "MONGO_DB_URL"
MONGO_DATABASE_NAME = "rec_sys_db"
MONGO_COLLECTION_NAME = "rev_courses3"
MONGO_COURSE_COLLECTION_NAME = "course_indexing"